### ISSUE TITLE
Turkish character error.

### ISSUE THREAD

**Issue by Hasokeyk** [georgekhananaev/py-image-compressor#1]
There are Turkish characters in some of my visual files

For example:

Operatör
OperatФr

Does it usually replace Russian characters?

How do I fix this?

**Comment by ttm-tech** [comment]
Hi, you can decode/encode these characters, try this: https://toolbox.googleapps.com/apps/encode_decode/

**Comment by georgekhananaev** [comment]
Hi, you can decode/encode these characters, try this: https://toolbox.googleapps.com/apps/encode_decode/

**Comment by Hasokeyk** [comment]
But it is necessary to embed it in the code. I cannot do this for every file.

This process takes a long time for all files one by one. Our aim is to facilitate the visual compression process.

**Comment by georgekhananaev** [comment]
I understand. You can add a line of code that encodes and decodes all characters. There's a multithreaded pool that acts like a loop; you can probably insert it there. It might also be related to your operating system. I need to experiment with it to understand the issue. If I have free time, maybe this weekend or the next, I will release an update. Cheers.
